name: 构建 immich_model-cache 并推送 Docker 镜像

on:
  workflow_dispatch: # 手动触发


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        remove-android: 'true'
        remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: 检出代码
      uses: actions/checkout@v2

    # 设置 Docker Buildx
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 登录到 cnb
    - name: 登录到 cnb
      run:
          docker login docker.cnb.cool -u cnb -p ${{ secrets.cnb }}


    # 构建并推送多平台 Docker 镜像
    - name: 构建并推送多平台 Docker 镜像
      uses: docker/build-push-action@v4
      with:
        context: .
        file: torchserve/Dockerfile
        platforms: |
          linux/amd64
        push: true
        tags: |
          docker.cnb.cool/xkand/xx/docker_torchserve_actions:latest
